version: "3.9"
services:
  postgresdb:
    container_name: db
    image: postgres:14.4-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=qr-codes
    ports:
      - "5432:5432"
  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3
    ports:
      - "4566:4566"
  redis:  
    image: redis:7.0.4-alpine
    ports:
      - "6379:6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Warsaw
      - DB_SOURCE=postgresql://postgres:postgres@db:5432/qr-codes?sslmode=disable
      - ADDR=:8080
      - ENV=dev
      - AWS_BUCKET_NAME=bucketo
      - AWS_BUCKET_REGION=us-east-1
      - CDN_ADDRESS=http://localhost:4566/bucketo/
      - APP_URL=http://localhost:8080/
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=
      - LOCALSTACK_URL=http://localstack:4566
    depends_on:
      - postgresdb
    entrypoint: ["/app/wait-for.sh","postgresdb:5432","--", "/app/start.sh"]
    command: ["/app/main"]