// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type Group struct {
	ID          int64     `json:"id"`
	Owner       string    `json:"owner"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type QrCode struct {
	Uuid           string    `json:"uuid"`
	Owner          string    `json:"owner"`
	GroupID        int64     `json:"group_id"`
	UsagesCount    int64     `json:"usages_count"`
	RedirectionUrl string    `json:"redirection_url"`
	Title          string    `json:"title"`
	Description    string    `json:"description"`
	StorageUrl     string    `json:"storage_url"`
	CreatedAt      time.Time `json:"created_at"`
}

type Redirect struct {
	ID         int64     `json:"id"`
	QrCodeUuid string    `json:"qr_code_uuid"`
	Ipv4       string    `json:"ipv4"`
	Isp        string    `json:"isp"`
	State      string    `json:"state"`
	Country    string    `json:"country"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	FullName  string    `json:"full_name"`
	Password  string    `json:"password"`
	CreatedAt time.Time `json:"created_at"`
}
