// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCode, error)
	CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGroupByOwnerAndID(ctx context.Context, arg DeleteGroupByOwnerAndIDParams) error
	DeleteQRCode(ctx context.Context, arg DeleteQRCodeParams) error
	GetGroupByOwnerAndID(ctx context.Context, arg GetGroupByOwnerAndIDParams) (Group, error)
	GetGroupByOwnerAndIDForUpdate(ctx context.Context, arg GetGroupByOwnerAndIDForUpdateParams) (Group, error)
	GetGroupsByOwner(ctx context.Context, arg GetGroupsByOwnerParams) ([]Group, error)
	GetGroupsCountByOwner(ctx context.Context, owner string) (int64, error)
	GetQRCode(ctx context.Context, uuid string) (QrCode, error)
	GetQRCodeForUpdate(ctx context.Context, uuid string) (QrCode, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserByUsernameOrEmail(ctx context.Context, arg GetUserByUsernameOrEmailParams) (User, error)
	IncrementQRCodeEntries(ctx context.Context, uuid string) error
	UpdateGroupByOwnerAndID(ctx context.Context, arg UpdateGroupByOwnerAndIDParams) (Group, error)
}

var _ Querier = (*Queries)(nil)
