// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: redirect.sql

package db

import (
	"context"
)

const createRedirect = `-- name: CreateRedirect :one
INSERT INTO redirects (qr_code_uuid, ipv4, isp, autonomous_sys, lat, lon, city, country)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8)
RETURNING id, qr_code_uuid, ipv4, isp, autonomous_sys, lat, lon, city, country, created_at
`

type CreateRedirectParams struct {
	QrCodeUuid    string `json:"qr_code_uuid"`
	Ipv4          string `json:"ipv4"`
	Isp           string `json:"isp"`
	AutonomousSys string `json:"autonomous_sys"`
	Lat           string `json:"lat"`
	Lon           string `json:"lon"`
	City          string `json:"city"`
	Country       string `json:"country"`
}

func (q *Queries) CreateRedirect(ctx context.Context, arg CreateRedirectParams) (Redirect, error) {
	row := q.db.QueryRowContext(ctx, createRedirect,
		arg.QrCodeUuid,
		arg.Ipv4,
		arg.Isp,
		arg.AutonomousSys,
		arg.Lat,
		arg.Lon,
		arg.City,
		arg.Country,
	)
	var i Redirect
	err := row.Scan(
		&i.ID,
		&i.QrCodeUuid,
		&i.Ipv4,
		&i.Isp,
		&i.AutonomousSys,
		&i.Lat,
		&i.Lon,
		&i.City,
		&i.Country,
		&i.CreatedAt,
	)
	return i, err
}
